In [99]:
import numpy as np
a = np.array([5,4,3,2,1])
b = a + 0.5
c = np.array([1.0,2.2,6,4,5])

In [100]:
d = np.vstack((a,b,c)).transpose()

In [101]:
d

array([[ 5. ,  5.5,  1. ],
       [ 4. ,  4.5,  2.2],
       [ 3. ,  3.5,  6. ],
       [ 2. ,  2.5,  4. ],
       [ 1. ,  1.5,  5. ]])

In [102]:
d.transpose()

array([[ 5. ,  4. ,  3. ,  2. ,  1. ],
       [ 5.5,  4.5,  3.5,  2.5,  1.5],
       [ 1. ,  2.2,  6. ,  4. ,  5. ]])

In [103]:
np.corrcoef(d.transpose())

array([[ 1.        ,  1.        , -0.76081087],
       [ 1.        ,  1.        , -0.76081087],
       [-0.76081087, -0.76081087,  1.        ]])

In [80]:
D = d.transpose().dot(d) 

In [69]:
D

array([[ 55.  ,  62.5 ,  35.  ],
       [ 62.5 ,  71.25,  42.5 ],
       [ 35.  ,  42.5 ,  55.  ]])

In [67]:
np.linalg.eig(D)

(array([  1.56106987e+02,  -1.45253793e-14,   2.51430130e+01]),
 array([[-0.57559335, -0.73363244, -0.36121426],
        [-0.66340203,  0.67719918, -0.31827506],
        [-0.47811091, -0.05643326,  0.87648459]]))

In [68]:
np.linalg.inv(D)

array([[  3.04931225e+14,  -2.81474977e+14,   2.34562481e+13],
       [ -2.81474977e+14,   2.59823055e+14,  -2.16519213e+13],
       [  2.34562481e+13,  -2.16519213e+13,   1.80432677e+12]])